remote_theme: mmistakes/so-simple-theme
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
skin: "/assets/css/skins/dark.css"

# Site settings
title: 
description: 
url: https://outsider7542.github.io/onemoretest
logo: "/assets/logo/lockten-tech-high-resolution-logo-transparentbg.png"

# Navigation links
navigation:
  - title: Home
    url: /
  - title: Services
    url: /services/
  - title: Contact
    url: /contact/
